firstproj/firstproj/urls.py
from django.contrib import admin
from django.urls import path

from sunapp.views import hello,hello1,hello2,student
from students.views import listone,listall
from students.views import post,post1,postform
from students.views import delete,edit
from CookieSessionApp import views as csviews
from flower import views as fviews
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',hello),
    path('hello1/<str:username>',hello1),
    path('hello2/<str:username>',hello2),
    path('stds/',student),
    path('listone/',listone),
    path('listall/',listall),
    path('post/',post),
    path('post1/',post1),
    path('postform/',postform),
    path('delete/<str:stdId>/',delete),
    path('edit/<str:stdId>/<str:mode>/',edit),
    path('edit/<str:stdId>/',edit),

    # cookies
    path('set_cookie/<str:key>/<str:value>/', csviews.set_cookie),
	path('set_cookie2/<str:key>/<str:value>/', csviews.set_cookie2),
	path('get_cookie/<str:key>/', csviews.get_cookie),
	path('get_allcookies/', csviews.get_allcookies),
	path('delete_cookie/<str:key>/', csviews.delete_cookie),
    path('pagecount/', csviews.pagecount),
    # sessions
    path('set_session/<str:key>/<str:value>/', csviews.set_session),
	path('get_session/<str:key>/', csviews.get_session),
	path('get_allsessions/', csviews.get_allsessions),
	# vote
	path('vote/', csviews.vote),	
	path('set_session2/<str:key>/<str:value>/', csviews.set_session2),
	path('delete_session/<str:key>/', csviews.delete_session),
    # login
	path('login/', csviews.login),	
	path('logout/', csviews.logout),


    path('mypage/',csviews.mypage),
    path('adduser/',csviews.adduser),
    path('register/',csviews.register),
    path('flower/', fviews.flowers),
    path('flower/<slug:slug>/', fviews.detail, name='detail'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstproj/urls.py
from django.contrib import admin
from django.urls import path,include

from sunapp.views import hello,hello1,hello2,student
from students.views import listone,listall
from students.views import post,post1,postform
from students.views import delete,edit
from CookieSessionApp import views as csviews
from flower import views as fviews
from django.conf import settings 
from django.conf.urls.static import static
from news import views as nviews
from boardapp import views as bviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',hello),
    path('hello1/<str:username>',hello1),
    path('hello2/<str:username>',hello2),
    path('stds/',student),
    path('listone/',listone),
    path('listall/',listall),
    path('post/',post),
    path('post1/',post1),
    path('postform/',postform),
    path('delete/<str:stdId>/',delete),
    path('edit/<str:stdId>/<str:mode>/',edit),
    path('edit/<str:stdId>/',edit),

    # cookies
    path('set_cookie/<str:key>/<str:value>/', csviews.set_cookie),
	path('set_cookie2/<str:key>/<str:value>/', csviews.set_cookie2),
	path('get_cookie/<str:key>/', csviews.get_cookie),
	path('get_allcookies/', csviews.get_allcookies),
	path('delete_cookie/<str:key>/', csviews.delete_cookie),
    path('pagecount/', csviews.pagecount),
    # sessions
    path('set_session/<str:key>/<str:value>/', csviews.set_session),
	path('get_session/<str:key>/', csviews.get_session),
	path('get_allsessions/', csviews.get_allsessions),
	# vote
	path('vote/', csviews.vote),	
	path('set_session2/<str:key>/<str:value>/', csviews.set_session2),
	path('delete_session/<str:key>/', csviews.delete_session),
    # login
	path('login/', csviews.login),	
	path('logout/', csviews.logout),


    path('mypage/',csviews.mypage),
    path('adduser/',csviews.adduser),
    path('register/',csviews.register),

    path('newsindex/', nviews.index),
	path('newsindex/<str:pageindex>/', nviews.index),
	path('newsdetail/<int:detailid>/', nviews.detail),
	path('newslogin/', nviews.login),
	path('newslogout/', nviews.logout),
	path('newsadminmain/', nviews.adminmain),
	path('newsadminmain/<str:pageindex>/', nviews.adminmain),
 	path('newsadd/', nviews.newsadd),
	path('newsedit/<int:newsid>/', nviews.newsedit),
	path('newsedit/<int:newsid>/<str:edittype>/', nviews.newsedit),
	path('newsdelete/<int:newsid>/', nviews.newsdelete),
	path('newsdelete/<int:newsid>/<str:deletetype>/', nviews.newsdelete),

    #post
    path('showpost/', bviews.showpost),
    path('showpost/<str:pageindex>/', bviews.showpost),
    path('addpost/', bviews.addpost),
    path('captcha/', include('captcha.urls')),

    # allauth
    path('accounts/', include('allauth.urls')),

    path('flower/', fviews.flowers),
    path('flower/create/', fviews.create, name='create'),
    path('flower/edit/<int:pk>/', fviews.edit, name='edit'),
    path('flower/delete/<int:pk>/', fviews.delete, name='delete'),
    path('flower/<slug:slug>/', fviews.detail, name='detail'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstproj/CookieSessionApp/models.py
from django.db import models

# Create your models here.

firstproj/flower/models.py
from django.db import models
from django.utils.text import slugify 
from django.urls import reverse
# Create your models here.

# 定義分類名稱欄位
class Category(models.Model):

    title = models.CharField(max_length=255, default="")

    def __str__(self):

        return self.title

# 定義標籤名稱欄位   
class Tag(models.Model):
    title = models.CharField(max_length=255, default="")

    def __str__(self):
        return self.title
    
# 定義商品資料欄位    
class Flower(models.Model):

    title = models.CharField(max_length=255, default="")

    description = models.TextField(default="")

    slug = models.SlugField(blank=True, default="") 
    category = models.ForeignKey(Category, null=True, on_delete=models.PROTECT) 
    tags = models.ManyToManyField(Tag)
    image = models.ImageField(default="", blank=True, upload_to="images")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title) 
        super(Flower, self).save()

    def get_absolute_url(self):
        return reverse("detail", args=[str(self.slug)])

firstproj/sunapp/models.py
from django.db import models

# Create your models here.

firstproj/CookieSessionApp/views.py
from django.shortcuts import render, redirect

# 匯入相關套件
from django.http import HttpResponse
import datetime
# login authentication
from django.contrib.auth import authenticate
from django.contrib import auth
from django.contrib.auth.models import User

# Create your views here.
# 新增設定cookie函式
def set_cookie(request,key=None,value=None):
	response = HttpResponse('Cookie 儲存完畢!')
	response.set_cookie(key, value)
	return response
    
# 新增取得cookie函式
def get_cookie(request,key=None):
	if key in request.COOKIES:
		return HttpResponse('%s : %s' %(key,request.COOKIES[key]))
	else:
		return HttpResponse('Cookie 不存在!')

# 新增設定cookie函式，加入有效時間
def set_cookie2(request,key=None,value=None):
	response = HttpResponse('Cookie 有效時間1小時!')
	response.set_cookie(key,value,max_age=3600)
	return response			

# 新增刪除cookie函式	
def delete_cookie(request,key=None):
    if key in request.COOKIES:
        response = HttpResponse('Delete Cookie: '+key)	
        response.delete_cookie(key)
        return response
    else:
        return HttpResponse('No cookies:' + key)

# 瀏覽次數計算
def pagecount(request):
	if "counter" in request.COOKIES:
		counter=int(request.COOKIES["counter"])
		counter+=1
	else:		
		counter=1
	response = HttpResponse('今日瀏覽次數：' + str(counter))		
	tomorrow = datetime.datetime.now() + datetime.timedelta(days = 1)
	tomorrow = datetime.datetime.replace(tomorrow, hour=0, minute=0, second=0)
	expires = datetime.datetime.strftime(tomorrow, "%a, %d-%b-%Y %H:%M:%S GMT") 
	response.set_cookie("counter", counter, expires=expires)
	return response

# 顯示所有cookies
def get_allcookies(request):
	if request.COOKIES!=None:
		strcookies=""
		for key1,value1 in request.COOKIES.items():
			strcookies= strcookies + key1 + ":" + value1 + "<br>"
		return HttpResponse('%s' %(strcookies))
	else:
		return HttpResponse('Cookie 不存在!')
        
# 新增設定session函式
def set_session(request,key=None,value=None):
	response = HttpResponse('Session 儲存完畢!')
	request.session[key]=value
	return response

# 新增取得session函式
def get_session(request,key=None):
	if key in request.session:
		return HttpResponse('%s : %s' %(key,request.session[key]))
	else:
		return HttpResponse('Session 不存在!')
		
# 新增投票函式，並存入session中
def vote(request):
	if not "vote" in request.session:
		request.session["vote"]=True
		msg="您第一次投票!"		
	else:		
		msg="您已投過票!"			
	response = HttpResponse(msg)		
	return response					

# 顯示所有sessions
def get_allsessions(request):
	if request.session!=None:
		strsessions=""
		for key1,value1 in request.session.items():
			strsessions= strsessions + key1 + ":" + str(value1) + "<br>"
		return HttpResponse(strsessions)
	else:
		return HttpResponse('Session 不存在!')	

# 新增設定session函式，持續時間30秒
def set_session2(request,key=None,value=None):
	response = HttpResponse('Session 儲存完畢!')
	request.session[key]=value
	request.session.set_expiry(30) # 設持續的時間為30秒
	return response

# 新增刪除session函式
def delete_session(request,key=None):
	if key in request.session:
		response = HttpResponse('Delete Session: '+key)	
		del request.session[key]
		return response
	else:
		return HttpResponse('No Session:' + key)
"""	
def login(request):
	#預設帳號密碼
	username = "jeng"
	password = "1234"
	if request.method == 'POST':
		if not 'username' in request.session:
			if request.POST['username']==username and request.POST['password']==password:
				request.session['username']=username #儲存Session
				mess=username + " 您好，登入成功！"
				status="login"
	else:
		if 'username' in request.session:
			if request.session['username']==username:
				mess=request.session['username'] + " 您已登入過了！"
				status="login"				
	return render(request, 'login.html',locals())
	
def logout(request):
	if 'username' in request.session:
		mess=request.session['username'] + ' 您已登出!'
		del request.session['username']	#刪除Session	
	return render(request, 'login.html',locals())
"""

def mypage(request):
	if request.user.is_authenticated:
	   name=request.user.username
	return render(request, "mypage.html", locals())

def login(request):
	if request.method == 'POST':
		name = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=name, password=password)
		if user is not None:
			if user.is_active:
				auth.login(request,user)
				return redirect('/mypage/')
				mess = '登入成功！'
			else:
				mess = '帳號尚未啟用！'
		else:
			mess = '登入失敗！'
	return render(request, "login.html", locals())
	
def logout(request):
	auth.logout(request)
	return redirect('/mypage/')	

def adduser(request):	
	try:
		user=User.objects.get(username="test")
	except:
		user=None
	if user!=None:
		mess = user.username + " 帳號已建立!"
		return HttpResponse(mess)
	else:	# 建立 test 帳號			
		user=User.objects.create_user("test","test@test.com.tw","a123456!")
		user.first_name="wen" # 姓名
		user.last_name="lin"  # 姓氏
		user.is_staff=True	# 工作人員狀態
		user.save()
		return redirect('/admin/')
	
def register(request):	
	if request.method == "POST":      #如果是以POST方式才處理
		username = request.POST['username'] #取得表單輸入資料
		password = request.POST['password']
		email =  request.POST['email']
		first_name =  request.POST['first_name']
		last_name = request.POST['last_name']
		user=User.objects.create_user(username,email,password)
		user.first_name=first_name # 姓名
		user.last_name=last_name  # 姓氏
		user.save()
	else:
		mess = '請輸入資料'
	return render(request, "register.html", locals())
	

firstproj/flower/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from flower.models import Flower
# Create your views here.

def flowers(request):
    q = request.GET.get('q', None)
    flowers = '' 
    if q is None or q is "":
        flowers = Flower.objects.all() 
    elif q is not None:
        flowers = Flower.objects.filter(title__contains=q)
    return render(request, 'flower.html', {'flowers': flowers })

def detail(request, slug=None):
    flower = get_object_or_404(Flower, slug=slug)
    return render(request, 'detail.html', locals())

firstproj/students/views.py
from django.shortcuts import render,redirect

from students.models import student
from students.form import PostForm

def listone(request):
    try:
        unit = student.objects.get(stdName="s1")
    except:
        errormessage = "讀取錯誤!"
    return render(request, "listone.html",locals())

def listall(request):
    allStudents = student.objects.all().order_by('id')
    return render(request,"listall.html",locals())


def post(request):
    if request.method == "POST":
        mess = request.POST['stdName']
        mess = mess + " " + request.POST['stdId']
        mess = mess + " " + request.POST['stdSex']
        mess = mess + " " + request.POST['stdBirth']
        mess = mess + " " + request.POST['stdAddress']
        mess = mess + " " + request.POST['stdPhone']
        mess = mess + " " + request.POST['stdEmail']

    else:
        mess = "資料表單尚未送出!"
    return render(request, "addstudent.html", locals())

def post1(request):
    if request.method == "POST":
        stdName = request.POST['stdName']
        stdId = request.POST['stdId']
        stdSex = request.POST['stdSex']
        stdBirth =  request.POST['stdBirth']
        stdAddress =  request.POST['stdAddress']
        stdPhone =  request.POST['stdPhone']
        stdEmail =  request.POST['stdEmail']
        unit = student.objects.create(stdName=stdName, stdId=stdId,stdSex=stdSex,stdBirth=stdBirth, stdAddress=stdAddress,stdPhone=stdPhone,stdEmail=stdEmail)
        unit.save()
        return redirect('/post1')
    else:
        mess = "請輸入資料(資料不作驗證)"

    return render(request, "addstudent1.html",  locals())    

def postform(request):
    stdform = PostForm()
    return render(request, "stdform.html",  locals())


def delete(request, stdId = None):
    if stdId != None:
        if request.method == "POST":
            stdId = request.POST["stdId"]
        try:
            unit = student.objects.get(stdId=stdId)
            unit.delete()
            return redirect('delete.html')
        except:
            mess = "查無該學號"
    return render(request, "delete.html",  locals())

def edit(request, stdId = None ,mode= None):
    if mode == "edit":
        unit = student.objects.get(stdId=stdId)
        unit.stdName = request.GET["stdName"]
        unit.stdId = request.GET["stdId"]
        unit.stdSex = request.GET["stdSex"]
        unit.stdBirth = request.GET["stdBirth"]
        unit.stdEmail = request.GET["stdEmail"]
        unit.stdPhone = request.GET["stdPhone"]
        unit.stdAddress = request.GET["stdAddress"]
        unit.save()
        mess = "已修改完成"
        return redirect('/hello')
    else:
        try:
            unit = student.objects.get(stdId=stdId)
            strDate = str(unit.stdBirth)
            strDate2 = strDate.replace(" 年 ", "-")
            strDate2 = strDate.replace(" 月 ", "-")
            strDate2 = strDate.replace(" 日 ", "-")
            unit.stdBirth = strDate2
        except:
            mess = "該學號不存在"
    return render(request, "edit.html",  locals())

firstproj/sunapp/views.py
from django.shortcuts import render
import random
from django.http import HttpResponse
from datetime import datetime
def student(request):
    std1 = {"name": "SUN", "sid": "1111", "age":"18" }
    std2 = {"name": "KAI", "sid": "1112", "age":"18" }
    std3 = {"name": "PEI", "sid": "1113", "age":"18" }
    stds = [std1,std2,std3]
    return render(request,'std.html',locals())
    
    
def hello(request):

    #return HttpResponse("Hello World");
    return render(request,'hello.html')
    
def hello1(request,username):
    now = datetime.now()
    return render(request,'hello1.html',locals())
#globl全域變數
times = 0;
def hello2(request,username):
    global times
    times = times + 1
    local_times = times
    now = datetime.now()
    dice1 = dice()
    dice2 = dice()
    dice3 = dice()
    
    score = random.randint(0,100)
    #dict1 = {"dice1": dice1, "dice2": dice2, "dice3": dice3}
    return render(request,'hello2.html', locals())
    
def dice():
    return  random.randint(1,6)
    
    

flower/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from flower.models import Flower
from .forms import FlowerForm
# Create your views here.

def flowers(request):
    q = request.GET.get('q', None)
    flowers = '' 
    if q == None or q == "":
        flowers = Flower.objects.all() 
    elif q is not None:
        flowers = Flower.objects.filter(title__contains=q)
    return render(request, 'flower/flower.html', {'flowers': flowers })

def detail(request, slug=None):
    flower = get_object_or_404(Flower, slug=slug)
    return render(request, 'flower/detail.html', locals())
def create(request):
    if request.method == 'POST':
        form = FlowerForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/flower/')
    else:
        form = FlowerForm()
    return render(request, 'flower/edit.html', {'form': form})

def edit(request, pk=None):
    flower = get_object_or_404(Flower, pk=pk)
    if request.method == "POST":
        form = FlowerForm(request.POST, instance=flower)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/flower/')
    else:
        form = FlowerForm(instance=flower)

    return render(request, 'flower/edit.html', {'form': form})
def delete(request, pk=None):
    flower = get_object_or_404(Flower, pk=pk)
    flower.delete()

    return render(request, 'flower/')

firstproj/templates/addstudent.html
{% extends "base.html" %}
{% block title %} 顯示所有資料{% endblock %}
{% block content %}
<!--製作表單-->
<form action="/post/" method="POST" name = "addstd">
    {% csrf_token %}
    <div> 
        <br>請輸入姓名 : <input type = "text" name = "stdName" />
        <br>請輸入ID : <input type = "text" name = "stdId" />
        
        <br>請輸入性別：
        <input type = "radio" id = "std1" value ="M" name = "stdSex" checked = "checked"/>
        男生
        <input type = "radio" id = "std2" value ="F" name = "stdSex"/>
        女生
        <br>請輸入生日 : <input type = "date" name = "stdBirth" />
        <br>請輸入地址 : <input type = "text" name = "stdAddress" />
        <br>請輸入電話 : <input type = "text" name = "stdPhone" />
        <br>請輸入電子郵件 : <input type = "text" name = "stdEmail" />
        
        <br> <input type="submit" value="送出資料" />
    </div> 
    <div> 接收資料：{{mess}}</div>
</form>
{% endblock %}

firstproj/templates/addstudent1.html
{% extends "base.html" %}
{% block title %} 顯示所有資料{% endblock %}
{% block content %}
<h2> student 表單新增(一)</h2>

<!--製作表單-->
<form action="." method="POST" name = "form1">
    {% csrf_token %}
    <table class = "table table-dark">
    <tr>
        <th> 姓名</th><td><input type ="text" id = "stdName" name ="stdName"/></td>
    </tr> 
    <tr>
        <th> 學號</th><td><input type ="text" id = "stdId" name ="stdId"/></td>
    </tr>
    <tr>
        <th> 性別</th>
        <td>
            <input name = "stdSex" type = "radio" id ="stdSex1" value = "M" checked = "checked"/>
            男生
            <input name = "stdSex" type = "radio" id ="stdSex2" value = "F" />          
            女生
        </td>
    </tr>  
    <tr>
        <th> 生日</th><td><input type ="date" id = "stdBirth" name ="stdBirth"/></td>
    </tr>
    <tr>
        <th> 地址</th><td><input type ="text" id = "stdAddress" name ="stdAddress"/></td>
    </tr>
    <tr>
        <th> 電話</th><td><input type ="text" id = "stdPhone" name ="stdPhone"/></td>
    </tr>
    <tr>
        <th> 電子郵件</th><td><input type ="text" id = "stdEmail" name ="stdEmail"/></td>
    </tr>
    <tr>
        <th colspan="2" align="center">
        <input type="submit" name = "button" id = "button" value="送出">
        <input type="reset" name = "button2" id = "button2" value="重設">
    </tr>
    </table>
    <span style="color:red">{{mess}}</span>
    <div> 接收資料：{{mess}}</div>
</form>
{% endblock %}

firstproj/templates/delete.html
{% extends "base.html" %}
{% block title %} 顯示所有資料{% endblock %}
{% block content %}

<h2>student資料表刪除</h2>
<form action="." method="POST" name = "form1">
    {% csrf_token %}
    <table class = "table" >
    <div >輸入編號：<input type="text" name="stdId"/></div>
    </div><input type="submit" id="button" value= "確認刪除"/></div>

    <span style="color:red"> {{mess}} </span>
    </table>
    </form>
{% endblock %}

firstproj/templates/detail.html
{% extends "base.html" %}
{% block title %}顯示花朵資料{% endblock %}
{% block content %}
<br>
<br>
<br>
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">{{ flower.title }}</h1>
            <div class="lead">{{ flower.description }}</div>
        </div>
    </div>
    <a href="/flower/">Back</a>
{% endblock %}

firstproj/templates/edit.html
{% extends "base.html" %}
{% block title %} 顯示所有資料{% endblock %}
{% block content %}

<h2>student資料表編輯</h2>
<form action="/edit/{{unit.stdId}}/edit" method="GET" name = "form1">
    {% csrf_token %}
    <table class = "table table-dark" >
        <tr>
            <th>性名</th><td><input type ="test" id="stdName" name="stdName" value={{unit.stdName}}></td>
        </tr>
        <tr>
            <th>學號</th><td><input type ="test" id="stdId" name="stdId" value={{unit.stdId}}></td>
        </tr>
        <tr>
            <th>性別</th>
            {% if unit.stdSex == "M" %}
            <td>
                <input type ="radio" id="stdSex1" name="stdSex" value="M" checked="checked"></td>
                男生
                <input type ="radio" id="stdSex2" name="stdSex" value="F" checked="checked"></td>
                女生
            {% else %}
                <input type ="radio" id="stdSex1" name="stdSex" value="M" checked="checked"></td>
                男生
                <input type ="radio" id="stdSex2" name="stdSex" value="F" checked="checked"></td>
                女生
            {% endif %}
        </tr>
        <tr>
            <th>生日</th><td><input type ="test" id="stdBirth" name="stdBirth" value={{unit.stdBirth}}></td>
        </tr>
        <tr>
            <th>地址</th><td><input type ="test" id="stdAddress" name="stdAddress" value={{unit.stdAddress}}></td>
        </tr>
        <tr>
            <th>電話</th><td><input type ="test" id="stdPhone" name="stdPhone" value={{unit.stdPhone}}></td>
        </tr>
        <tr>
            <th>電子郵件</th><td><input type ="test" id="stdEmail" name="stdEmail" value={{unit.stdEmail}}></td>
        </tr>
        <tr>
            <th colspan="2">
            <button type="submit" class = "btn btn-primary" name="button" id = "button" >送出</button>
            <button type="reset" class = "btn btn-primary" name="button2" id = "button" >送出</button>
        </tr>
    </table>
    <span style="color:red"> {{mess}} </span>
</form>
{% endblock %}

firstproj/templates/flower.html
{% extends "base.html" %}
{% block title %}顯示花朵資料{% endblock %}
{% block content %}
<br>
<br>
<br>
    <div class="card-columns">
    {% for flower in flowers %}
    <div class="card">
        <div class="card-body">
 
            <h5 class="card-title"><a href="{% url 'detail' flower.slug %}">{{ flower.title }}</a></h5>
            <img class="card-img-top" src="{{ flower.image.url }}" alt="Card image cap">
            <p class="card-text">{{ flower.description | truncatechars:100 }}</p>
            <a href="#" class="card-link">{{ flower.category }}</a>
            <a href="/admin/flower/flower/{{ flower.id }}/change/" class="card-link">Edit</a>
            <a href="/admin/flower/flower/{{ flower.id }}/delete/" class="card-link">Delete</a>
            <hr>
 
            All flowers in the <strong>{{ flower.category }}</strong> category:<br>
            {% for c_flower in flower.category.flower_set.all %}
                <a href="#" class="card-link">{{ c_flower }}</a><br>
            {% endfor %}
        </div>
    </div>
{% endfor %}
    </div>
{% endblock %}

firstproj/templates/hello.html
{% extends "base.html" %}
{% block title %} hello {% endblock %}
{% block content %}

<body>
	<h1>Hello Django</h1>
</body>

{% endblock %}

firstproj/templates/hello1.html
{% extends "base.html" %}
{% block title %} hello1 {% endblock %}
{% block content %}
<body>
	<h1>歡迎{{username}}</h1>
	<h2>時間{{now}}</h2>
</body>

{% endblock %}

firstproj/templates/hello2.html
{% extends "base.html" %}
{% block title %} {% load static %}<link href = "{% static 'css/style.css'%}" rel = "stylesheet" type = "text/css" /> {% endblock %}

{% block content %}

<body>
	<img src = "{% static 'images/ball.png'%}" alt ="歡迎" width ="32" height = "32">
	<h1 class="info">歡迎{{username}}</h1>
	<h2 >時間:{{now}}</h2>
	<h2 >點數1:{{dict1.dice1}}</h2>
	<h2 >點數2:{{dict1.dice2}}</h2>
	<h2 >點數3:{{dict1.dice3}}</h2>
	<h2 >次數:{{local_times}}</h2>
	<h2 >等第:{{score}} <br>
		{% if score >= 90%}
			A
		{% elif score >= 80%}
			B
		{% elif score >= 70%}
			C
		{% elif score >= 60%}
			D
		{% else %}
			E
		{% endif%}
	</h2>

</body>


{% endblock %}

firstproj/templates/listone.html
{% extends "base.html" %}
{% block title %} 顯示一筆資料{% endblock %}
{% block content %}
    <body>
	    <h2 >顯示studnt 資料表一筆資料	</h2>
        編號:{{unit.id}} <br/>
        姓名:{{unit.stdName}} <br/>
        學號:{{unit.stdId}} <br/>
        性別:{{unit.stdSex}} <br/>
        生日:{{unit.stdBirth}} <br/>
        地址:{{unit.stdAdress}} <br/>
        電話:{{unit.stdPhone}} <br/>
        電子郵件:{{unit.Email}} <br/>
    <body>
{% endblock %}

firstproj/templates/login.html
{% extends "base.html" %}
{% block title %}登入頁面{% endblock %}
{% block content %}
<br>
<br>
<br>
	<form action="/login/" method="POST" name="form1">
		{% csrf_token %}
		{% if status == "login" %}
			<div><a href="/logout/">登出系統</a></div>
		{% else %}
			<div>帳號：<input type="text" name="username" id="username"/></div>
			<div>密碼：<input type="password" name="password" id="password"/></div> 
			<div><input type="submit" name="button" id="button" value="登入" /></div>	
		{% endif %}   
		<span style="color:red">{{mess}}</span>
	</form>
{% endblock %}

firstproj/templates/std.html
<html>
<head>
	{% load static %}<link href = "{% static 'css/style.css'%}" rel = "stylesheet" type = "text/css" />
</head>
<body>
	<h2 >
		{% for std in stds %}
			<h2> 第{{forloop.counter}}位學生 </h2>
			<ul>
				<li>名字：{{std.name}}</li>
				<li>學號：{{std.sid}}</li>
				<li>年齡：{{std.age}}</li>
			</ul>
		{% empty %}
			沒有任何資料~
		{% endfor %}
	</h2>
</body>
</html>